export const ON_LOGIN = "on/login";
export const ON_LOGOUT = "on/logout";
export const ME_FETCH ="me/fetch";
export const ME_LOGIN = "me/login";
export const USER_FETCH ="user/fetch";
export const FETCH_GROUPS = "fetch/groups"; 
export const GROUPS_QUERY_CHANGED = "groups/query_changed";
export const GROUPS_QUERY_COMPLETED ="groups/query_completed";

export const SELECT_GROUPID ="groups/id";
export const FETCH_ONE_GROUP ="group/group_fetch";
export const FETCH_ONE_GROUP_COMPLETED = "group/group_fetch_completed";
export const FETCH_ONE_GROUP_ERROR = "group/group_fetch_error";
export const SELECT_USERID ="user/id";
export const FETCH_USERS = "fetch/users"; 
export const FETCH_ONE_USER ="user/user_fetch";
export const FETCH_ONE_USER_COMPLETED = "user/user_fetch_completed";
export const FETCH_ONE_USER_ERROR = "user/user_fetch_error";
export const FETCH_PEOPLE ="fetch/people";